db:
  host: "dbhost"
  name: "dbname"
  username: "db_username"
  ssl_mode: "db_ssl_mode"
  port: "db_port"
http_server:
  port: "http_server_port"
auth:
  access_token_ttl: 15m
  refresh_token_ttl: 720h